In [ ]:
# Error en el IDE, correr comando en terminal
# pip install --upgrade jupyter notebook jupyterlab
# Error de modulos -> Reinstalar venv y correr antes de requirements
# python -m pip install --upgrade pip setuptools wheel

In [19]:
#Importar las librerias
from pathlib import Path
import sys

# Carpeta raíz del proyecto
project_root = Path.cwd().parent

if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
    
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly.express as px 
from data_profiling import ProfileReport
import webbrowser
import os
import warnings
from tqdm import TqdmWarning 

warnings.filterwarnings("ignore", category=TqdmWarning)
warnings.filterwarnings("ignore")

In [2]:
# Dataset Obtenido: https://www.kaggle.com/datasets/hassanjameelahmed/store-sales/data

df = pd.read_csv('../data/store_sales.csv')
df.head(5)

,CustomerID,Age,Gender,Category,ItemPurchased,Amount,Season,PaymentMethod,ItemRating,DiscountApplied(%),PreviousPurchases
0,1,58,Female,Accessories,Handbag,115.50,Autumn,Card,3.5,18,4
1,2,40,Male,Mens Clothing,Shirt,103.43,Spring,Card,4.1,13,4
2,3,66,Female,Sports,Football,35.45,Spring,Card,3.3,11,3
3,4,39,Female,Accessories,Handbag,153.31,Spring,Card,4.4,13,4
4,5,23,Female,Home,Curtains,151.43,Winter,Card,4.1,20,10

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CustomerID          5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Gender              5000 non-null   object
 3   Category            5000 non-null   object
 4   ItemPurchased       5000 non-null   object
 5   Amount              5000 non-null   float64
 6   Season              5000 non-null   object
 7   PaymentMethod       5000 non-null   object
 8   ItemRating          5000 non-null   float64
 9   DiscountApplied(%)  5000 non-null   int64
 10  PreviousPurchases   5000 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 429.8+ KB

In [4]:
df.describe()

,CustomerID,Age,Amount,ItemRating,DiscountApplied(%),PreviousPurchases
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,45.224800,285.090522,3.784160,14.983600,5.008800
std,1443.520003,14.564995,551.454382,0.681796,5.988063,2.194285
min,1.000000,20.000000,5.080000,1.100000,0.000000,0.000000
25%,1250.750000,33.000000,70.547500,3.300000,11.000000,3.000000
50%,2500.500000,45.000000,122.485000,3.800000,15.000000,5.000000
75%,3750.250000,58.000000,184.535000,4.300000,19.000000,6.000000
max,5000.000000,70.000000,2997.940000,5.000000,36.000000,13.000000

In [5]:
df.isna().sum()

CustomerID            0
Age                   0
Gender                0
Category              0
ItemPurchased         0
Amount                0
Season                0
PaymentMethod         0
ItemRating            0
DiscountApplied(%)    0
PreviousPurchases     0
dtype: int64

In [9]:
print(df.duplicated().sum())

0

In [11]:
profile = ProfileReport(
    df,
    title="EDA",
    explorative=True
)

profile.to_file("../reports/EDA.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 11/11 [00:00<00:00, 627.65it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
webbrowser.open("file://" + os.path.abspath("../reports/EDA.html"))

True

In [20]:
df['Category'].value_counts()

Category
Footwear           983
Sports             835
Womens Clothing    547
Beauty             529
Mens Clothing      511
Electronics        507
Accessories        470
Groceries          332
Home               286
Name: count, dtype: int64

In [21]:
df_category = df.groupby('Category')['Amount'].sum().sort_values(ascending=False).reset_index()

sns.barplot(data = df_category, x = 'Category', y = 'Amount', hue='Category', palette='coolwarm', legend=False)
plt.xticks(rotation = 45)
plt.xlabel('Category')
plt.ylabel('Amount')
plt.tight_layout()
plt.show()